import { MetadataRoute } from "next";

const BASE_URL = "https://www.gildre.com";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    // Core pages
    { url: BASE_URL,                                   lastModified: new Date(), changeFrequency: "weekly",  priority: 1.0 },
    { url: `${BASE_URL}/founder-community`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.95 },
    { url: `${BASE_URL}/membership`,                   lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE_URL}/memberprograms`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE_URL}/content`,                      lastModified: new Date(), changeFrequency: "weekly",  priority: 0.8 },
    { url: `${BASE_URL}/contact`,                      lastModified: new Date(), changeFrequency: "yearly",  priority: 0.7 },
    { url: `${BASE_URL}/mentor`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/referral`,                     lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${BASE_URL}/propellantventures`,           lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/mindhappy`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/solvee`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/podcast`,                      lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${BASE_URL}/gatherly`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/matchplaygroup`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/privacy`,                      lastModified: new Date(), changeFrequency: "yearly",  priority: 0.3 },
    // City pages
    { url: `${BASE_URL}/boston`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/austin`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/bayarea`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/nyc`,                          lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/la`,                           lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/chicago`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/seattle`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    // Blog — founder stories
    { url: `${BASE_URL}/blog/one-to-three-million-arr-founder-community`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/blog/dr-michael-filosi-fullarton-park-dental-adelaide`,       lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/christof-gomez-mannfeld-solvee-ai-business-coach`,      lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/florian-kemmerich-vocating-ai-impact-investor`,       lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/alex-jekowski-cents-laundromat-tech-vertical-saas`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/cody-graham-sogo-restaurant-app-chicago`,           lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/iliana-alvarado-ensyx-it-governance-ai-mexico`,     lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/frances-pratt-more-sales-less-marketing`,           lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/steve-ramona-servant-heart-podcast-networking`,     lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/sharon-gai-keynote-speaker-alibaba-ai`,           lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/chris-yeh-blitzscaling-reid-hoffman`,              lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/chris-tsakalakis-stubhub-ceo-marketplace`,        lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/russell-breuer-spot-tango-pet-food-founder`,      lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/fritz-lanman-classpass-microsoft-unicorn`,       lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/james-corwin-wildlife-artist-corwin-galleries`,  lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/aytekin-tank-bootstrapped-jotform-no-vc`,       lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/alex-bean-divvy-billcom-acquisition`,            lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/nasa-engineer-y-combinator-chatopensource`,      lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/robyn-hobson-cape-town-to-us-cmo`,              lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/luke-ashenbrand-princeton-football-startup`,     lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/john-lionberger-broadway-engineer-racing`,       lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/armando-vera-carvajal-hangtight-amazon`,        lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/ryan-hughes-google-snapchat-fan-pier-labs`,     lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/john-olson-healthcare-entrepreneur-coaching`,      lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/elise-madrick-cerene-executive-transformation`,   lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/chris-riklin-topline-professional-marketplace`,  lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE_URL}/blog/nelson-brooks-cabana-boys-shark-tank-founder`,   lastModified: new Date(), changeFrequency: "yearly", priority: 0.8 },
    // Blog — SEO articles
    { url: `${BASE_URL}/blog/accelerator-vs-peer-community-founder-difference`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/equity-free-founder-networks-gildre-mentor-access`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/fellowship-vs-membership-founder-community`,                lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/finding-advisors-who-actually-exited-founder-community`,    lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/founder-communities-ranked-revenue-stage-matching`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/founder-community-product-market-fit`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/founder-isolation-200k-arr-peer-community`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/founder-loneliness-predictable-stage-peer-support`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/founder-proximity-bias-test-market-fit`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/gildre-founder-community-scaling-stage-ceos`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/healthtech-founders-find-mentors-who-exited`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/on-deck-vs-gildre-founder-community`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/pre-revenue-founder-stage-matched-peer-community`,          lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/solo-saas-founder-pivot-decision-who-to-talk-to`,           lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/under-500k-arr-founder-community-stage-matched`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/why-founder-isolation-happens-first-two-years`,             lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/founder-isolation-support-vs-understanding-peer-mentorship`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/co-founder-startup-isolation-peer-scarcity-not-headcount`,  lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/honest-startup-feedback-why-founders-rarely-get-it`,        lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/zero-to-500k-arr-why-generic-startup-advice-fails`,         lastModified: new Date(), changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE_URL}/blog/gildre-july-2026-25-percent-growth-zero-churn-product-market-fit`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/blog/why-59-dollars-beats-gatekeeping-accessible-founder-community`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    // Guides & articles
    { url: `${BASE_URL}/guides/building-products-that-scale`,                 lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/micro-influencer-marketing`,                   lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/bootstrapping-vs-venture-capital`,             lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/cap-table-management`,                         lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/when-to-say-no-to-customers`,                   lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/first-100-customers`,                           lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/startup-fundraising-terminology`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/startup-equity-101`,                           lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/equity-dilution-explained`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/next-100-customers-gtm-playbook`,              lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/how-to-use-customer-feedback-build-product`,   lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/pre-seed-fundraising-playbook`,                lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE_URL}/guides/building-high-performing-sdr-team`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
  ];
}
